// learn/exercise-pack.js — AI 题包 (§9.3): per-card quiz material generated by the
// user's OWN chat engine. See docs/learning-design.md §9.3 and interaction-spec
// 「掌握阶梯与技能轮换」.
//
// Deliberately a SEPARATE module and version from notes.js: folding the pack into
// the notes prompt would bump the notes PROMPT_VERSION and re-charge every card's
// already-paid parse — §9.2's version discipline allows bumps only to correct
// wrong output (rejection recorded in §12). Transport, capability gate and cache
// discipline are all §9.2's, reused: LearnNotes.chat carries the wire formats,
// LearnNotes.capable() is the gate, and the record shape {id, data, at, v} lives
// in the SAME `notes` store under a derived key (no new store, no index change,
// no DB_VERSION bump). Device-local, never synced — a regenerable derivative.
//
// Cost contract (§9.3): at most ONE call per card per PACK_VERSION; generated only
// when the rotation lands on an AI exercise with a cache miss; in-flight deduped;
// a failed cache write never surfaces as failure and never baits a second charge.
//
// EXTENSION PAGES ONLY (and the app's WKWebView) — same hosts as notes.js.

var LearnExercisePack = (() => {
  const PACK_VERSION = 1;

  // Derived cache key in the `notes` store. NUL never appears in an item id
  // (16 hex chars), so pack records can never collide with note records.
  function packKey(id) { return String(id) + '\u0000pack'; }

  // Same normalization contract as LearnModel.clozeNorm.
  function norm(s) {
    return String(s == null ? '' : s).toLowerCase().replace(/[\s\p{P}\p{S}]+/gu, '');
  }

  function capable() {
    return typeof LearnNotes !== 'undefined' && LearnNotes.capable();
  }

  // English system prompt (project convention); question text in the user's UI
  // language. JSON-only so the parser has a fighting chance. Every rule stated
  // here is ALSO enforced mechanically in parsePack — a prompt is an instruction
  // a model can ignore (§9.2's lesson).
  function buildPrompt(explainLang) {
    return 'You are generating quiz material for one sentence a learner is '
      + 'studying. The learner studies the language the Sentence is written in; '
      + 'the Translation is in the learner\'s own language and is context only. '
      + 'Respond with ONLY a JSON object, no markdown, in exactly this shape: '
      + '{"mcq":{"distractors":["...","...","..."]},'
      + '"listen":{"foils":["...","..."]},'
      + '"comprehension":[{"q":"...","options":["...","..."],"correct":0}],'
      + '"accept":{"<word>":["..."]}} '
      + 'Rules: mcq.distractors are 3 plausible but INCORRECT translations of the '
      + 'Sentence, written in the same language as the Translation, each clearly '
      + 'different in meaning from the Translation. listen.foils are 4 to 6 single '
      + 'words in the Sentence\'s language that sound plausible in its context but '
      + 'do NOT occur in the Sentence. comprehension is 1 or 2 multiple-choice '
      + 'questions about the Sentence\'s meaning — question and options written in '
      + (explainLang || 'zh-CN') + ', 2 to 4 options each, "correct" is the '
      + 'zero-based index of the right option. accept maps words copied verbatim '
      + 'from the Sentence to alternative spellings or forms a learner might '
      + 'type (optional). Keep every string short.';
  }

  // Model output is untrusted input. Parse defensively, then enforce each rule
  // mechanically; violators are dropped PER FIELD (a partial pack is still a
  // pack), and only a pack with nothing usable is bad_output.
  function parsePack(text, item) {
    let s = String(text == null ? '' : text).trim();
    s = s.replace(/^```[a-z]*\s*/i, '').replace(/```\s*$/, '');
    const a = s.indexOf('{'), b = s.lastIndexOf('}');
    if (a < 0 || b <= a) return null;
    let j;
    try { j = JSON.parse(s.slice(a, b + 1)); } catch (_) { return null; }
    if (!j || typeof j !== 'object') return null;

    const out = {};
    const trN = norm(item && item.tr);
    const sentLower = String((item && item.text) || '').toLowerCase();

    // mcq.distractors — must not restate the translation (equal or containing
    // either way after normalization: an option that IS the answer in disguise
    // makes the exercise unwinnable-by-honesty).
    const ds = [];
    const dSeen = new Set([trN]);
    for (const d of (j.mcq && Array.isArray(j.mcq.distractors)) ? j.mcq.distractors : []) {
      if (typeof d !== 'string' || !d.trim()) continue;
      const n = norm(d);
      if (!n || dSeen.has(n)) continue;
      if (trN && (n === trN || n.indexOf(trN) >= 0 || trN.indexOf(n) >= 0)) continue;
      dSeen.add(n); ds.push(d.trim());
      if (ds.length >= 3) break;
    }
    if (ds.length) out.mcq = { distractors: ds };

    // listen.foils — must NOT occur in the sentence (a foil that was actually
    // heard punishes a correct ear).
    const foils = [];
    const fSeen = new Set();
    for (const f of (j.listen && Array.isArray(j.listen.foils)) ? j.listen.foils : []) {
      if (typeof f !== 'string' || !f.trim()) continue;
      const n = norm(f);
      if (!n || fSeen.has(n)) continue;
      if (sentLower.indexOf(f.trim().toLowerCase()) >= 0) continue;
      fSeen.add(n); foils.push(f.trim());
      if (foils.length >= 6) break;
    }
    if (foils.length) out.listen = { foils };

    // comprehension — well-typed MCQs only; `correct` must be in range.
    const comp = (Array.isArray(j.comprehension) ? j.comprehension : [])
      .filter((c) => c && typeof c.q === 'string' && c.q.trim()
        && Array.isArray(c.options) && c.options.length >= 2 && c.options.length <= 4
        && c.options.every((o) => typeof o === 'string' && o.trim())
        && Number.isInteger(c.correct) && c.correct >= 0 && c.correct < c.options.length)
      .map((c) => ({ q: c.q.trim(), options: c.options.map((o) => o.trim()), correct: c.correct }))
      .slice(0, 2);
    if (comp.length) out.comprehension = comp;

    // accept — keys verbatim from the sentence (the §9.2 rule, same reason);
    // alternates must actually differ from the key after normalization.
    if (j.accept && typeof j.accept === 'object' && !Array.isArray(j.accept)) {
      const acc = {};
      for (const k of Object.keys(j.accept)) {
        if (sentLower.indexOf(String(k).toLowerCase()) < 0) continue;
        const kN = norm(k);
        const alts = (Array.isArray(j.accept[k]) ? j.accept[k] : [])
          .filter((x) => typeof x === 'string' && x.trim())
          .map((x) => x.trim())
          .filter((x) => { const n = norm(x); return n && n !== kN; })
          .slice(0, 4);
        if (alts.length) acc[k] = alts;
      }
      if (Object.keys(acc).length) out.accept = acc;
    }

    return Object.keys(out).length ? out : null;
  }

  // In-flight generations by card id — same double-charge guard as notes.js.
  const inflight = new Map();

  // Cache-first; at most one charge per card per PACK_VERSION.
  async function get(item, explainLang) {
    if (inflight.has(item.id)) return inflight.get(item.id);
    const hit = await LearnStore.getNote(packKey(item.id));
    if (hit && hit.data && hit.v === PACK_VERSION) return { data: hit.data, cached: true };
    if (inflight.has(item.id)) return inflight.get(item.id);
    const p = (async () => {
      const user = 'Sentence (' + (item.lang || 'und') + '): ' + item.text
        + '\nTranslation: ' + item.tr;
      const text = await LearnNotes.chat(buildPrompt(explainLang), user);
      const data = parsePack(text, item);
      if (!data) {
        try { console.error('[learn/pack] bad_output:', String(text).slice(0, 500)); } catch (_) {}
        const e = new Error('unusable pack output'); e.code = 'bad_output'; throw e;
      }
      // Charge already happened, data in hand — a failed cache write must not
      // surface as failure and bait a second charge (same stance as notes.js).
      try { await LearnStore.putNote(packKey(item.id), data, { v: PACK_VERSION }); } catch (_) {}
      return { data, cached: false };
    })();
    inflight.set(item.id, p);
    try { return await p; } finally { inflight.delete(item.id); }
  }

  // Version-gated read, never a charge.
  function cached(id) {
    return LearnStore.getNote(packKey(id))
      .then((h) => (h && h.data && h.v === PACK_VERSION ? h : null))
      .catch(() => null);
  }

  return { PACK_VERSION, packKey, capable, buildPrompt, parsePack, get, cached };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = LearnExercisePack;
