// AUTO-GENERATED by build.js from build/palette.config.js — do not edit by hand.
window.MT_PALETTE = {"textColor":"#56633f","ytTextColor":"#ccdbb2","brand":"#c67139","brandBtnBg":"rgba(198,113,57,.92)","chipOn":"#56633f","chipOnHover":"rgba(114,129,87,.08)"};
window.MT_PALETTE.roundBtnCss = function (fontPx) {
  return 'border:none;cursor:pointer;background:' + window.MT_PALETTE.brandBtnBg +
    ';color:#fff;font-size:' + (fontPx || 15) + 'px;font-weight:700;';
};
