// AUTO-GENERATED by build.js from build/palette.config.js — do not edit by hand.
window.MT_PALETTE = {"textColor":"#56633f","ytTextColor":"#ccdbb2","brand":"#c67139","brandBtnBg":"rgba(198,113,57,.92)","chipOn":"#56633f","chipOnHover":"rgba(114,129,87,.08)","overlayEnText":"#ffffff","overlayFailText":"#ffb3b3","overlayPendingText":"#d6d6d6","overlayRowBg":"rgba(8,8,8,0.82)","overlayMenuBg":"rgba(28,28,28,.97)","overlayMenuText":"#eeeeee","overlayMenuDim":"#9a9a9a","overlayMenuSep":"rgba(255,255,255,.12)","overlayMenuHover":"rgba(255,255,255,.1)","overlayTick":"#728157","overlayChipRadius":"8px","overlayPanelRadius":"16px","overlayControlRadius":"999px"};
window.MT_PALETTE.roundBtnCss = function (fontPx) {
  return 'border:none;cursor:pointer;background:' + window.MT_PALETTE.brandBtnBg +
    ';color:#fff;font-size:' + (fontPx || 15) + 'px;font-weight:700;';
};
